import streamlit as st
import pandas as pd
from google import genai
from google.genai import types
import os
import json
import base64
import re
import logging
from typing import List, Dict, Any, Optional
from io import BytesIO
from pydantic import BaseModel, Field, field_validator, ValidationInfo, ValidationError

# --- PDF GENERATION IMPORTS ---
try:
    from reportlab.lib.pagesizes import letter
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, ListFlowable, ListItem
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.enums import TA_JUSTIFY, TA_LEFT
    from reportlab.lib import colors
    HAS_REPORTLAB = True
except ImportError:
    HAS_REPORTLAB = False

# --- LOGGING CONFIGURATION ---
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)
logger = logging.getLogger("MaritimePOC")

# --- CONSTANTS ---
API_KEY_NAME = "GEMINI_API_KEY"
STORE_ID_NAME = "STORE_ID"
MODEL_ID = "gemini-2.5-flash"

SYSTEM_INSTRUCTION = """
You are a Maritime Rules of the Road expert and Examiner.
CRITICAL: You MUST use the File Search tool to search ALL documents in the knowledge base.

RULES FOR OPERATION:
1. Search across ALL these documents for every question.
2. Do NOT answer from general knowledge. 
3. Always cite specific Rule numbers (e.g., "Rule 14(a)") or Annex sections.
4. Ensure accuracy by using the exact terminology found in the documents.
5. When quoting rule text verbatim, use brief excerpts (1-3 sentences maximum per rule).
6. Intersperse verbatim quotes with your own explanations and analysis.
7. DO NOT reproduce entire paragraphs or pages verbatim - select only the most relevant sentences.
"""

# --- DOMAIN LAYER (Models) ---

class QuizQuestion(BaseModel):
    """Represents a standardized quiz question."""
    question: str = Field(..., description="The question text")
    options: List[str] = Field(..., description="List of possible answers")
    correct_answer: str = Field(..., description="The text of the correct answer")
    reference: str = Field(..., description="Rule citation")
    explanation: str = Field(..., description="Reasoning for the answer")

class TopicDistribution(BaseModel):
    """Configuration for AI generation topics."""
    topic_name: str
    percentage: int

class QuizRequest(BaseModel):
    """Validates configuration for Quiz Generation."""
    num_questions: int = Field(..., ge=1, le=25)
    topics: List[TopicDistribution] = Field(default_factory=list)

    @field_validator('topics')
    @classmethod
    def validate_total_percentage(cls, topics: List[TopicDistribution], info: ValidationInfo) -> List[TopicDistribution]:
        if not topics:
            return []
        total = sum(t.percentage for t in topics)
        if total != 100:
            raise ValueError(f"Total percentage must equal 100%. Current: {total}%")
        return topics

# --- INFRASTRUCTURE LAYER (External IO) ---

class PDFGenerator:
    """Handles PDF generation using ReportLab."""
    
    @staticmethod
    def create_study_guide(content: str) -> Optional[BytesIO]:
        if not HAS_REPORTLAB:
            return None

        buffer = BytesIO()
        doc = SimpleDocTemplate(
            buffer, 
            pagesize=letter,
            rightMargin=72, leftMargin=72,
            topMargin=72, bottomMargin=18
        )
        
        styles = getSampleStyleSheet()
        story = []

        styles.add(ParagraphStyle(name='RuleTitle', parent=styles['Heading2'], spaceAfter=6, textColor=colors.darkblue))
        styles.add(ParagraphStyle(name='NormalJustified', parent=styles['Normal'], alignment=TA_JUSTIFY, spaceAfter=6))

        story.append(Paragraph("Maritime Remediation Study Guide", styles['Title']))
        story.append(Spacer(1, 12))
        story.append(Paragraph("Generated by Maritime AI PoC", styles['Normal']))
        story.append(Spacer(1, 24))

        lines = content.split('\n')
        
        for line in lines:
            line = line.strip()
            if not line:
                story.append(Spacer(1, 6))
                continue

            formatted_line = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', line)
            
            if line.startswith('#'):
                clean_text = line.lstrip('#').strip().replace('**', '') 
                story.append(Paragraph(clean_text, styles['RuleTitle']))
                story.append(Spacer(1, 6))
            elif line.startswith('- ') or line.startswith('* '):
                clean_text = formatted_line[2:].strip()
                story.append(Paragraph(f"• {clean_text}", styles['NormalJustified']))
            elif re.match(r'^\d+\.', line):
                story.append(Paragraph(formatted_line, styles['NormalJustified']))
            else:
                story.append(Paragraph(formatted_line, styles['NormalJustified']))

        try:
            doc.build(story)
            buffer.seek(0)
            return buffer
        except Exception as e:
            logger.error(f"PDF Generation failed: {e}")
            return None

class GenAIProvider:
    """Encapsulates Google GenAI interactions."""
    
    def __init__(self, api_key: str, store_id: str):
        self.client = genai.Client(api_key=api_key)
        self.store_id = store_id
        self.model = MODEL_ID

    def generate_content(
        self, 
        prompt: str, 
        system_instr: str, 
        use_rag: bool = True,
        response_schema: Any = None
    ) -> str:
        try:
            tools = []
            if use_rag and self.store_id:
                tools = [types.Tool(
                    file_search=types.FileSearch(file_search_store_names=[self.store_id])
                )]

            config_args = {
                "temperature": 0.1,
                "system_instruction": system_instr,
                "safety_settings": [
                     {"category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_NONE"},
                     {"category": "HARM_CATEGORY_HATE_SPEECH", "threshold": "BLOCK_NONE"},
                     {"category": "HARM_CATEGORY_SEXUALLY_EXPLICIT", "threshold": "BLOCK_NONE"},
                     {"category": "HARM_CATEGORY_DANGEROUS_CONTENT", "threshold": "BLOCK_NONE"},
                ]
            }
            if tools: config_args["tools"] = tools
            
            response = self.client.models.generate_content(
                model=self.model,
                contents=prompt,
                config=types.GenerateContentConfig(**config_args)
            )
            
            if response.text:
                return response.text
            
            if response.candidates:
                candidate = response.candidates[0]
                if candidate.content and candidate.content.parts:
                    parts_text = [p.text for p in candidate.content.parts if p.text]
                    if parts_text:
                        return "".join(parts_text)
                
                if candidate.finish_reason:
                    reason = str(candidate.finish_reason)
                    if "RECITATION" in reason:
                        raise ValueError("RECITATION_ERROR")
                    raise ValueError(f"AI Generation stopped. Reason: {reason}")

            raise ValueError("The AI returned an empty response (No candidates or text found).")

        except Exception as e:
            if "RECITATION_ERROR" in str(e):
                raise e 
            logger.error(f"GenAI generation failed: {e}")
            raise RuntimeError(str(e))

class DataManager:
    """Handles File I/O operations."""
    
    @staticmethod
    @st.cache_data(ttl=3600) 
    def load_csv_sample(filepath: str, selected_tags: List[str], sample_size: int) -> List[Dict[str, Any]]:
        if not os.path.exists(filepath): return []
        try:
            df = pd.read_csv(filepath)
            if "Meta_Tags" not in df.columns: return []
            
            def matches_tags(row_tags):
                if pd.isna(row_tags): return False
                row_tag_list = [t.strip() for t in str(row_tags).split(',')]
                return any(tag in row_tag_list for tag in selected_tags)

            filtered_df = df[df['Meta_Tags'].apply(matches_tags)]
            if filtered_df.empty: return []
            
            sample = filtered_df.sample(n=min(len(filtered_df), sample_size))
            return sample.to_dict(orient="records")
        except Exception: return []

    @staticmethod
    @st.cache_data(ttl=3600)
    def get_topics_from_csv(filepath: str) -> List[str]:
        if not os.path.exists(filepath): return ["General Rules"]
        try:
            df = pd.read_csv(filepath)
            if "Meta_Tags" in df.columns:
                all_tags = set()
                for tag_string in df["Meta_Tags"].dropna():
                    tags = [tag.strip() for tag in str(tag_string).split(',')]
                    all_tags.update(tags)
                return sorted(list(all_tags))
        except Exception: return ["General Rules"]
        return ["General Rules"]

    @staticmethod
    def get_base64_image(filepath: str) -> Optional[str]:
        if not os.path.exists(filepath): return None
        try:
            with open(filepath, 'rb') as f: data = f.read()
            return base64.b64encode(data).decode()
        except Exception: return None

# --- SERVICE LAYER (Business Logic) ---

class JSONParser:
    @staticmethod
    def parse(text: Optional[str]) -> List[Dict[str, Any]]:
        if not text: raise ValueError("AI response empty.")
        clean_text = re.sub(r'```json\s*', '', text)
        clean_text = re.sub(r'```', '', clean_text).strip()
        
        start = clean_text.find('[')
        end = clean_text.rfind(']') + 1
        
        if start != -1 and end != 0:
            return json.loads(clean_text[start:end])
        raise ValueError("No JSON array found.")

class QuizService:
    def __init__(self, ai_provider: GenAIProvider):
        self.ai = ai_provider

    def calculate_topic_distribution(self, request: QuizRequest) -> Dict[str, int]:
        distribution = {}
        total = request.num_questions
        assigned = 0
        active = [t for t in request.topics if t.percentage > 0]
        
        for i, topic in enumerate(active):
            if i == len(active) - 1: count = total - assigned
            else: count = int(total * (topic.percentage / 100))
            if count > 0:
                distribution[topic.topic_name] = count
                assigned += count
        return distribution

    def generate_from_ai(self, request: QuizRequest) -> List[QuizQuestion]:
        dist = self.calculate_topic_distribution(request)
        dist_str = "\n".join([f"- {c} questions about: {t}" for t, c in dist.items()])
        prompt = f"""
        Create a {request.num_questions} question multiple-choice quiz based ONLY on the provided File Store.
        DISTRIBUTION: {dist_str}
        OUTPUT SCHEMA (JSON Array): 
        [
            {{
                "question": "Question text...", 
                "options": ["A) ...", "B) ..."], 
                "correct_answer": "Full text of option", 
                "reference": "Rule #", 
                "explanation": "Concise explanation."
            }}
        ]
        """
        
        try:
            raw = self.ai.generate_content(prompt, SYSTEM_INSTRUCTION, use_rag=True)
            return [QuizQuestion(**i) for i in JSONParser.parse(raw)]
        except Exception as e:
            if "RECITATION_ERROR" in str(e):
                logger.warning("Quiz generation hit Recitation error. Retrying with paraphrase constraint.")
                prompt_safe = f"""
                Create a {request.num_questions} question multiple-choice quiz based on the provided File Store.
                DISTRIBUTION: {dist_str}
                
                CRITICAL INSTRUCTION: The previous attempt was blocked for quoting the text too closely.
                1. Rephrase the questions and options so they are distinct from the source text (Paraphrase).
                2. Test the concept/rule, do not just ask for the definition.
                3. Keep explanations concise and synthesized.
                
                OUTPUT SCHEMA (JSON Array): 
                [
                    {{
                        "question": "Question text (Paraphrased)...", 
                        "options": ["A) ...", "B) ..."], 
                        "correct_answer": "Full text of option", 
                        "reference": "Rule #", 
                        "explanation": "Synthesized explanation."
                    }}
                ]
                """
                raw = self.ai.generate_content(prompt_safe, SYSTEM_INSTRUCTION, use_rag=True)
                return [QuizQuestion(**i) for i in JSONParser.parse(raw)]
            raise e
    
    def generate_scenarios(self, request: QuizRequest) -> List[QuizQuestion]:
        dist = self.calculate_topic_distribution(request)
        dist_str = "\n".join([f"- {c} scenarios involving: {t}" for t, c in dist.items()])
        
        prompt = f"""
        Create a {request.num_questions} question *Navigational Scenario Quiz* based ONLY on the provided File Store.
        
        DISTRIBUTION:
        {dist_str}
        
        INSTRUCTIONS:
        1. **Do not ask simple definitions.**
        2. **Create vivid scenarios:** Describe what the Officer of the Watch sees (lights, day shapes, sound signals) or the radar plot.
        3. **Bridge Perspective:** Phrase questions as "You are a power-driven vessel steering 090. You see..."
        4. **Application:** Ask for the required action or identification of status.
        
        OUTPUT SCHEMA (JSON Array): 
        [
            {{
                "question": "Detailed scenario text...", 
                "options": ["A) ...", "B) ..."], 
                "correct_answer": "Full text of correct option", 
                "reference": "Rule #", 
                "explanation": "Concise explanation citing the rule."
            }}
        ]
        """
        
        try:
            raw = self.ai.generate_content(prompt, SYSTEM_INSTRUCTION, use_rag=True)
            return [QuizQuestion(**i) for i in JSONParser.parse(raw)]
        except Exception as e:
            if "RECITATION_ERROR" in str(e):
                logger.warning("Scenario generation hit Recitation error. Retrying with paraphrase constraint.")
                prompt_safe = f"""
                Create a {request.num_questions} question *Navigational Scenario Quiz* based on the provided File Store.
                DISTRIBUTION: {dist_str}
                
                CRITICAL INSTRUCTION: Do NOT copy scenario text from the books. Invent NEW scenarios that apply the same rules.
                1. Paraphrase all descriptions.
                2. Use different vessel names or slight variations in bearing/range to ensure uniqueness.
                
                OUTPUT SCHEMA (JSON Array): ... (Same as above)
                """
                raw = self.ai.generate_content(prompt_safe, SYSTEM_INSTRUCTION, use_rag=True)
                return [QuizQuestion(**i) for i in JSONParser.parse(raw)]
            raise e

    def generate_from_csv(self, raw_data: List[Dict], count: int) -> List[QuizQuestion]:
        prompt = f"""
        Convert this CSV data to JSON quiz. Use RAG for explanation/reference if missing.
        Data: {json.dumps(raw_data)}
        OUTPUT SCHEMA (JSON Array): [{{question, options[], correct_answer, reference, explanation}}]
        """
        raw = self.ai.generate_content(prompt, SYSTEM_INSTRUCTION, use_rag=True)
        return [QuizQuestion(**i) for i in JSONParser.parse(raw)]

class RemediationService:
    """Generates lesson plans with batch processing for scalability."""
    
    def __init__(self, ai_provider: GenAIProvider):
        self.ai = ai_provider

    def _generate_batch_content(self, batch_refs: List[str]) -> str:
        topics_context = ", ".join(batch_refs)
        
        prompt_high = f"""
        Create a "Deep Dive" remediation section for these specific Maritime Rules: {topics_context}.
        Based ONLY on the provided File Store documents.
        
        For each topic:
        1. **Header**: Rule Number/Name.
        2. **Official Rule Text**: Provide the exact verbatim text of the key sentence (1-3 sentences max).
        3. **Explanation**: Plain English summary.
        4. **Common Pitfalls**: Why students miss this.
        5. **Memory Aid**: Mnemonic or trick.
        
        OUTPUT FORMAT: Markdown. Do not include intro or outro.
        """
        
        try:
            return self.ai.generate_content(prompt_high, SYSTEM_INSTRUCTION, use_rag=True)
        except Exception as e:
            if "RECITATION_ERROR" in str(e):
                logger.warning(f"Batch {topics_context} hit Recitation error. Retrying with summary.")
                prompt_safe = f"""
                Create a "Deep Dive" remediation section for these specific Maritime Rules: {topics_context}.
                
                For each topic:
                1. **Header**: Rule Number/Name.
                2. **Rule Summary**: Summarize the rule concisely (Cite Rule #).
                3. **Explanation**: Plain English summary.
                4. **Common Pitfalls**: Why students miss this.
                5. **Memory Aid**: Mnemonic or trick.
                
                OUTPUT FORMAT: Markdown. Do not include intro or outro.
                """
                try:
                    return self.ai.generate_content(prompt_safe, SYSTEM_INSTRUCTION, use_rag=True)
                except Exception as e2:
                    return f"**Error generating content for {topics_context}: {str(e2)}**"
            return f"**System Error loading {topics_context}**"

    def generate_lesson(self, incorrect_questions: List[QuizQuestion]) -> str:
        unique_refs = sorted(list(set(q.reference for q in incorrect_questions if q.reference)))
        
        if not unique_refs:
            return "No specific rules identified for remediation."

        full_doc = [
            "# Remediation Lesson Plan",
            f"**Focus Topics:** {', '.join(unique_refs)}",
            "---"
        ]

        BATCH_SIZE = 3
        for i in range(0, len(unique_refs), BATCH_SIZE):
            batch = unique_refs[i:i+BATCH_SIZE]
            batch_content = self._generate_batch_content(batch)
            full_doc.append(batch_content)
            full_doc.append("\n---\n")

        full_doc.append("## Recommended Study Plan")
        full_doc.append("1. **Review** the specific rule citations above in your official handbook.")
        full_doc.append("2. **Practice** these topics using the 'Remediation Quiz' button below.")
        full_doc.append("3. **Visualize** the scenarios described in the 'Common Pitfalls' section.")

        return "\n\n".join(full_doc)

# --- PRESENTATION LAYER ---

def init_session_state():
    defaults = {
        "messages": [{"role": "assistant", "content": "👋 Maritime Expert Ready."}],
        "quiz_data": None,
        "current_quiz_source": None,
        "incorrect_questions": [],
        "remediation_text": None
    }
    for key, val in defaults.items():
        if key not in st.session_state:
            st.session_state[key] = val

def set_background():
    bin_str = DataManager.get_base64_image('background.png')
    if bin_str:
        st.markdown(f'''<style>
        .stApp {{ background-image: url("data:image/png;base64,{bin_str}"); background-size: cover; }}
        </style>''', unsafe_allow_html=True)

def main():
    st.set_page_config(page_title="RAG Engine", page_icon="⚓", layout="wide")
    set_background()
    init_session_state()
    
    try:
        ai_provider = GenAIProvider(st.secrets[API_KEY_NAME], st.secrets[STORE_ID_NAME])
        quiz_service = QuizService(ai_provider)
        remediation_service = RemediationService(ai_provider)
    except KeyError:
        st.error("Missing Secrets"); st.stop()

    with st.sidebar:
        st.title("⚓ Maritime AI")
        mode = st.radio("Tool:", ["Chat 🤖", "Quiz 📝"])
        if st.button("Reset Session"):
            st.session_state.messages = []
            st.session_state.quiz_data = None
            st.session_state.incorrect_questions = []
            st.session_state.remediation_text = None
            st.rerun()
        st.divider()
        st.caption("✅ v14.0 - Auto-Retry Fix") 

    if mode == "Chat 🤖":
        st.title("Regulations Chat")
        for m in st.session_state.messages: st.chat_message(m["role"]).write(m["content"])
        if p := st.chat_input():
            st.session_state.messages.append({"role": "user", "content": p})
            st.chat_message("user").write(p)
            with st.spinner("Thinking..."):
                try:
                    r = ai_provider.generate_content(p, SYSTEM_INSTRUCTION)
                    st.session_state.messages.append({"role": "assistant", "content": r})
                    st.chat_message("assistant").write(r)
                except Exception as e:
                    error_msg = f"Error: {e}"
                    st.session_state.messages.append({"role": "assistant", "content": error_msg})
                    st.chat_message("assistant").write(error_msg)

    elif mode == "Quiz 📝":
        st.title("Knowledge Check")
        
        def clear(): 
            st.session_state.quiz_data = None
            st.session_state.incorrect_questions = []
            st.session_state.remediation_text = None

        source = st.radio("Source:", ["CSV", "AI Gen"], horizontal=True, on_change=clear, key="source_radio")
        
        if source == "CSV":
            tags = st.multiselect("Topics:", DataManager.get_topics_from_csv("ror_test.csv"))
            n = st.number_input("Count:", 1, 25, 5)
            if st.button("Load CSV") and tags:
                try:
                    data = DataManager.load_csv_sample("ror_test.csv", tags, n)
                    if data:
                        with st.spinner("Generating quiz from CSV..."):
                            st.session_state.quiz_data = quiz_service.generate_from_csv(data, n)
                            st.session_state.current_quiz_source = "CSV"
                            st.rerun()
                    else:
                        st.warning("No data found for selected tags.")
                except Exception as e:
                    st.error(f"Error: {e}")
        else:
            quiz_style = st.radio("Quiz Style:", ["Standard Rules", "Applied Scenarios"], horizontal=True)
            st.divider()
            
            topics = []
            for i in range(1, 5):
                c1, c2 = st.columns([3, 1])
                t = c1.text_input(f"Topic {i}")
                p = c2.number_input(f"%", 0, 100, 0, key=f"p{i}")
                if t: topics.append(TopicDistribution(topic_name=t, percentage=p))
            
            n = st.number_input("Count", 1, 25, 5)
            
            current_total = sum(t.percentage for t in topics)
            st.progress(min(current_total, 100) / 100)
            if current_total == 100:
                st.success(f"Total: {current_total}% (Valid)")
            else:
                st.warning(f"Total: {current_total}% (Target: 100%)")

            if st.button(f"Generate {quiz_style}"):
                st.info("Generating Quiz... Please wait.")
                try:
                    req = QuizRequest(num_questions=n, topics=topics)
                    with st.spinner("Processing Documents..."):
                        if quiz_style == "Standard Rules":
                            st.session_state.quiz_data = quiz_service.generate_from_ai(req)
                            st.session_state.current_quiz_source = "AI (Standard)"
                        else:
                            st.session_state.quiz_data = quiz_service.generate_scenarios(req)
                            st.session_state.current_quiz_source = "AI (Scenarios)"
                        st.rerun()
                except ValueError as e:
                    # Fallback caught in Service, this catches irrecoverable errors
                    if "RECITATION_ERROR" in str(e):
                        st.error("The AI failed to paraphrase after retrying. Please select different topics.")
                    else:
                        st.error(f"Error: {e}")
                except Exception as e: 
                    st.error(f"Error: {e}")

        if st.session_state.quiz_data:
            st.divider()
            st.subheader(f"Quiz: {st.session_state.current_quiz_source}")
            questions = st.session_state.quiz_data
            
            with st.form("quiz"):
                score = 0
                answers = {}
                for i, q in enumerate(questions):
                    st.markdown(f"**{i+1}. {q.question}**")
                    answers[i] = st.radio("Opt", q.options, key=f"q{i}", label_visibility="collapsed", index=None)
                    st.write("---")
                
                if st.form_submit_button("Submit"):
                    current_incorrect = []
                    for i, q in enumerate(questions):
                        correct = q.correct_answer
                        user = answers.get(i)
                        
                        if user == correct:
                            score += 1
                            st.success(f"Q{i+1} Correct!")
                            st.write(f"**Question:** {q.question}")
                            st.write(f"**Your Answer:** {user}")
                        else:
                            st.error(f"Q{i+1} Incorrect")
                            st.write(f"**Question:** {q.question}")
                            st.write(f"**Your Answer:** {user}")
                            st.write(f"**Correct:** {correct}")
                            current_incorrect.append(q)
                            
                        with st.expander("Explanation"): st.info(f"{q.explanation} ({q.reference})")
                    
                    st.session_state.incorrect_questions = current_incorrect
                    st.session_state.remediation_text = None
                    pct = (score/len(questions))*100
                    st.metric("Score", f"{score}/{len(questions)} ({pct:.0f}%)")
            
            if st.session_state.incorrect_questions:
                st.divider()
                st.subheader("🎓 Remediation Zone")
                st.warning(f"You missed {len(st.session_state.incorrect_questions)} questions. Let's create a personalized lesson plan.")
                
                if st.button("Generate Remediation Lesson"):
                    with st.spinner("Analyzing weak points and generating lesson..."):
                        try:
                            lesson = remediation_service.generate_lesson(st.session_state.incorrect_questions)
                            st.session_state.remediation_text = lesson
                        except Exception as e:
                            st.error(f"System Error: {e}")
                
                if st.session_state.remediation_text:
                    st.markdown("---")
                    st.markdown(st.session_state.remediation_text)
                    
                    if HAS_REPORTLAB:
                        pdf_data = PDFGenerator.create_study_guide(st.session_state.remediation_text)
                        if pdf_data:
                            st.download_button(
                                label="📄 Download Study Guide (PDF)",
                                data=pdf_data,
                                file_name="remediation_plan.pdf",
                                mime="application/pdf"
                            )
                    else:
                        st.caption("Install 'reportlab' to enable PDF export.")

                    st.divider()
                    st.subheader("📝 Practice Makes Perfect")
                    
                    missed_refs = list(set([q.reference for q in st.session_state.incorrect_questions if q.reference]))
                    
                    c1, c2 = st.columns([3,1])
                    with c1:
                        st.info(f"Target Topics: {', '.join(missed_refs)}" if missed_refs else "Target Topics: General Review")
                    with c2:
                        rem_n = st.number_input("Questions:", 5, 25, 5, key="rem_n")
                    
                    rem_style = st.radio("Remediation Style:", ["Standard Rules", "Applied Scenarios"], horizontal=True, key="rem_style")

                    if st.button("Start Remediation Quiz"):
                        try:
                            topics = []
                            if missed_refs:
                                count = len(missed_refs)
                                base_pct = 100 // count
                                remainder = 100 % count
                                for i, ref in enumerate(missed_refs):
                                    pct = base_pct + (1 if i < remainder else 0)
                                    topics.append(TopicDistribution(topic_name=ref, percentage=pct))
                            else:
                                topics.append(TopicDistribution(topic_name="General Maritime Rules", percentage=100))
                            
                            req = QuizRequest(num_questions=rem_n, topics=topics)
                            
                            with st.spinner("Generating targeted practice quiz..."):
                                if rem_style == "Standard Rules":
                                    new_quiz = quiz_service.generate_from_ai(req)
                                else:
                                    new_quiz = quiz_service.generate_scenarios(req)
                                
                                st.session_state.quiz_data = new_quiz
                                st.session_state.current_quiz_source = f"Remediation ({rem_style})"
                                st.session_state.incorrect_questions = []
                                st.session_state.remediation_text = None
                                st.rerun()
                                
                        except ValueError as e:
                            if "RECITATION_ERROR" in str(e):
                                st.error("The AI attempted to copy too much text. Please try generating the quiz again.")
                            else:
                                st.error(f"Error: {e}")
                        except Exception as e:
                            st.error(f"System Error: {e}")

            with st.expander("Admin Export"):
                st.download_button("Download JSON", json.dumps([q.model_dump() for q in questions], indent=2), "quiz.json")

if __name__ == "__main__":
    main()