import streamlit as st
import pandas as pd
from google import genai
from google.genai import types
import os
import json
import base64
import re
import logging
from typing import List, Dict, Any, Optional, Union
from io import BytesIO
from pydantic import BaseModel, Field, field_validator, ValidationInfo, ValidationError
from concurrent.futures import ThreadPoolExecutor, as_completed

# --- PDF GENERATION IMPORTS ---
try:
    from reportlab.lib.pagesizes import letter
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, ListFlowable, ListItem
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.enums import TA_JUSTIFY, TA_LEFT
    from reportlab.lib import colors
    HAS_REPORTLAB = True
except ImportError:
    HAS_REPORTLAB = False

# --- LOGGING CONFIGURATION ---
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    datefmt='%Y-%m-%d %H:%M:%S'
)
logger = logging.getLogger("MaritimePOC")

# --- CONSTANTS ---
API_KEY_NAME = "GEMINI_API_KEY"
STORE_ID_NAME = "STORE_ID"
MODEL_ID = "gemini-2.5-flash"
TEMPERATURE = 0.1
REMEDIATION_BATCH_SIZE = 3
MAX_QUIZ_QUESTIONS = 25
MIN_QUIZ_QUESTIONS = 1
DEFAULT_QUIZ_COUNT = 5
CACHE_TTL_SECONDS = 3600
REMEDIATION_QUIZ_MIN = 5
REMEDIATION_QUIZ_MAX = 25
MAX_PARALLEL_WORKERS = 3
API_TIMEOUT_SECONDS = 120
BACKGROUND_IMAGE_CACHE_TTL = 86400  # 24 hours

SYSTEM_INSTRUCTION = """
You are a Maritime Rules of the Road expert and Examiner.
CRITICAL: You MUST use the File Search tool to search ALL documents in the knowledge base.

RULES FOR OPERATION:
1. Search across ALL these documents for every question.
2. Do NOT answer from general knowledge. 
3. Always cite specific Rule numbers (e.g., "Rule 14(a)") or Annex sections.
4. Ensure accuracy by using the exact terminology found in the documents.
5. When quoting rule text verbatim, use brief excerpts (1-3 sentences maximum per rule).
6. Intersperse verbatim quotes with your own explanations and analysis.
7. DO NOT reproduce entire paragraphs or pages verbatim - select only the most relevant sentences.
"""

# --- DOMAIN LAYER (Models) ---

class QuizQuestion(BaseModel):
    """Represents a standardized quiz question."""
    question: str = Field(..., description="The question text")
    options: List[str] = Field(..., description="List of possible answers")
    correct_answer: str = Field(..., description="The text of the correct answer")
    reference: str = Field(..., description="Rule citation")
    explanation: str = Field(..., description="Reasoning for the answer")

class TopicDistribution(BaseModel):
    """Configuration for AI generation topics."""
    topic_name: str
    percentage: int

class QuizRequest(BaseModel):
    """Validates configuration for Quiz Generation."""
    num_questions: int = Field(..., ge=1, le=25)
    topics: List[TopicDistribution] = Field(default_factory=list)

    @field_validator('topics')
    @classmethod
    def validate_total_percentage(cls, topics: List[TopicDistribution], info: ValidationInfo) -> List[TopicDistribution]:
        if not topics:
            return []
        total = sum(t.percentage for t in topics)
        if total != 100:
            raise ValueError(f"Total percentage must equal 100%. Current: {total}%")
        return topics

# --- INFRASTRUCTURE LAYER (External IO) ---

class PDFGenerator:
    """Handles PDF generation using ReportLab."""
    
    _BOLD_PATTERN = re.compile(r'\*\*(.*?)\*\*')
    _NUMBERED_PATTERN = re.compile(r'^\d+\.')
    
    @staticmethod
    def create_study_guide(content: str) -> Optional[BytesIO]:
        if not HAS_REPORTLAB:
            return None

        buffer = BytesIO()
        doc = SimpleDocTemplate(
            buffer, 
            pagesize=letter,
            rightMargin=72, leftMargin=72,
            topMargin=72, bottomMargin=18
        )
        
        styles = getSampleStyleSheet()
        story = []

        styles.add(ParagraphStyle(name='RuleTitle', parent=styles['Heading2'], spaceAfter=6, textColor=colors.darkblue))
        styles.add(ParagraphStyle(name='NormalJustified', parent=styles['Normal'], alignment=TA_JUSTIFY, spaceAfter=6))

        story.append(Paragraph("Maritime Remediation Study Guide", styles['Title']))
        story.append(Spacer(1, 12))
        story.append(Paragraph("Generated by Maritime AI PoC", styles['Normal']))
        story.append(Spacer(1, 24))

        lines = content.split('\n')
        
        for line in lines:
            line = line.strip()
            if not line:
                story.append(Spacer(1, 6))
                continue

            formatted_line = PDFGenerator._BOLD_PATTERN.sub(r'<b>\1</b>', line)
            
            if line.startswith('#'):
                clean_text = line.lstrip('#').strip().replace('**', '')
                story.append(Paragraph(clean_text, styles['RuleTitle']))
                story.append(Spacer(1, 6))
            elif line.startswith(('- ', '* ')):
                clean_text = formatted_line[2:].strip()
                story.append(Paragraph(f"• {clean_text}", styles['NormalJustified']))
            elif PDFGenerator._NUMBERED_PATTERN.match(line):
                story.append(Paragraph(formatted_line, styles['NormalJustified']))
            else:
                story.append(Paragraph(formatted_line, styles['NormalJustified']))

        try:
            doc.build(story)
            buffer.seek(0)
            return buffer
        except Exception as e:
            logger.error(f"PDF Generation failed: {e}")
            return None

class GenAIProvider:
    """Encapsulates Google GenAI interactions."""
    
    def __init__(self, api_key: str, store_id: str):
        self.client = genai.Client(api_key=api_key)
        self.store_id = store_id
        self.model = MODEL_ID

    def _get_config(self, system_instr: str, temperature: float = TEMPERATURE) -> types.GenerateContentConfig:
        """Helper to create config with tools and safety settings."""
        tools = []
        if self.store_id:
            tools = [types.Tool(
                file_search=types.FileSearch(file_search_store_names=[self.store_id])
            )]

        return types.GenerateContentConfig(
            temperature=temperature,
            system_instruction=system_instr,
            tools=tools,
            safety_settings=[
                {"category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_NONE"},
                {"category": "HARM_CATEGORY_HATE_SPEECH", "threshold": "BLOCK_NONE"},
                {"category": "HARM_CATEGORY_SEXUALLY_EXPLICIT", "threshold": "BLOCK_NONE"},
                {"category": "HARM_CATEGORY_DANGEROUS_CONTENT", "threshold": "BLOCK_NONE"},
            ]
        )

    def generate_content(
        self, 
        prompt: str, 
        system_instr: str, 
        use_rag: bool = True,
        response_schema: Any = None
    ) -> str:
        try:
            config = self._get_config(system_instr)
            response = self.client.models.generate_content(
                model=self.model,
                contents=prompt,
                config=config
            )
            
            if response.text:
                return response.text
            
            if response.candidates:
                candidate = response.candidates[0]
                if candidate.content and candidate.content.parts:
                    parts_text = [p.text for p in candidate.content.parts if p.text]
                    if parts_text:
                        return "".join(parts_text)
                
                if candidate.finish_reason:
                    reason = str(candidate.finish_reason)
                    if "RECITATION" in reason:
                        raise ValueError("RECITATION_ERROR")
                    raise ValueError(f"AI Generation stopped. Reason: {reason}")

            raise ValueError("The AI returned an empty response (No candidates or text found).")

        except Exception as e:
            if "RECITATION_ERROR" in str(e):
                raise e 
            logger.error(f"GenAI generation failed: {e}")
            raise RuntimeError(str(e))

    def generate_content_with_audio(
        self,
        prompt: str,
        audio_bytes: bytes,
        mime_type: str,
        system_instr: str
    ) -> str:
        """
        Generates content using Multimodal inputs (Text + Audio).
        """
        try:
            # Validate audio bytes
            if not audio_bytes:
                raise ValueError("Audio bytes are empty. Please ensure you recorded audio.")
            
            if len(audio_bytes) < 100:  # Very small audio files are likely invalid
                raise ValueError(f"Audio file is too small ({len(audio_bytes)} bytes). Please record a longer audio clip.")
            
            # Verify it's a valid WAV file (check for WAV header: "RIFF" at start, "WAVE" at offset 8)
            if mime_type == "audio/wav":
                if len(audio_bytes) < 12:
                    raise ValueError("Audio file is too small to be a valid WAV file.")
                if not (audio_bytes[:4] == b'RIFF' and audio_bytes[8:12] == b'WAVE'):
                    logger.warning("Audio file may not be a valid WAV format, but attempting to process anyway.")
            
            logger.info(f"Processing audio: {len(audio_bytes)} bytes, MIME type: {mime_type}")
            
            # Construct the parts: Prompt text first, then audio data
            # Some APIs expect the text instruction before the media
            parts = [
                prompt,
                types.Part.from_bytes(data=audio_bytes, mime_type=mime_type)
            ]
            
            config = self._get_config(system_instr, temperature=0.2)
            
            # Note: File Search tool works with text, but for grading audio 
            # we rely on the model's knowledge + the RAG context from the question generation phase.
            # We keep RAG enabled so it can look up the rule to grade against.
            
            response = self.client.models.generate_content(
                model=self.model,
                contents=parts,
                config=config
            )
            
            if response.text:
                return response.text
            
            if response.candidates:
                # Fallback logic for empty text
                if response.candidates[0].content.parts:
                    parts_text = [p.text for p in response.candidates[0].content.parts if p.text]
                    if parts_text:
                        return "".join(parts_text)
                
                # Check for finish reasons
                if response.candidates[0].finish_reason:
                    reason = str(response.candidates[0].finish_reason)
                    if "RECITATION" in reason:
                        logger.warning("Audio grading hit RECITATION error")
                        raise ValueError("RECITATION_ERROR")
                    raise ValueError(f"AI Generation stopped. Reason: {reason}")
            
            raise ValueError("No response generated for audio input.")

        except Exception as e:
            logger.error(f"Audio analysis failed: {e}")
            if "RECITATION_ERROR" in str(e):
                raise e
            raise RuntimeError(f"Audio grading failed: {str(e)}")

class DataManager:
    """Handles File I/O operations."""
    
    @staticmethod
    @st.cache_data(ttl=CACHE_TTL_SECONDS)
    def _load_full_csv(filepath: str) -> pd.DataFrame:
        if not os.path.exists(filepath):
            return pd.DataFrame()
        try:
            return pd.read_csv(filepath)
        except Exception as e:
            logger.warning(f"CSV loading error: {e}")
            return pd.DataFrame()
    
    @staticmethod
    @st.cache_data(ttl=CACHE_TTL_SECONDS) 
    def load_csv_sample(filepath: str, selected_tags: List[str], sample_size: int) -> List[Dict[str, Any]]:
        df = DataManager._load_full_csv(filepath)
        if df.empty or "Meta_Tags" not in df.columns:
            return []
        
        def matches_tags(row_tags):
            if pd.isna(row_tags): return False
            row_tag_list = [t.strip() for t in str(row_tags).split(',')]
            return any(tag in row_tag_list for tag in selected_tags)

        filtered_df = df[df['Meta_Tags'].apply(matches_tags)]
        if filtered_df.empty: return []
        
        sample = filtered_df.sample(n=min(len(filtered_df), sample_size), random_state=42)
        return sample.to_dict(orient="records")

    @staticmethod
    @st.cache_data(ttl=CACHE_TTL_SECONDS)
    def get_topics_from_csv(filepath: str) -> List[str]:
        df = DataManager._load_full_csv(filepath)
        if df.empty or "Meta_Tags" not in df.columns:
            return ["General Rules"]
        try:
            all_tags = set()
            for tag_string in df["Meta_Tags"].dropna():
                tags = [tag.strip() for tag in str(tag_string).split(',')]
                all_tags.update(tags)
            return sorted(list(all_tags))
        except Exception: return ["General Rules"]

    @staticmethod
    @st.cache_data(ttl=BACKGROUND_IMAGE_CACHE_TTL)
    def get_base64_image(filepath: str) -> Optional[str]:
        if not os.path.exists(filepath): return None
        try:
            with open(filepath, 'rb') as f: data = f.read()
            return base64.b64encode(data).decode()
        except Exception: return None

# --- SERVICE LAYER (Business Logic) ---

class JSONParser:
    @staticmethod
    def parse(text: Optional[str]) -> List[Dict[str, Any]]:
        if not text: raise ValueError("AI response empty.")
        clean_text = re.sub(r'```json\s*', '', text, flags=re.IGNORECASE)
        clean_text = re.sub(r'```', '', clean_text).strip()
        
        start = clean_text.find('[')
        end = clean_text.rfind(']') + 1
        
        if start == -1 or end == 0:
            # Try single object
            obj_start = clean_text.find('{')
            obj_end = clean_text.rfind('}') + 1
            if obj_start != -1 and obj_end != 0:
                try:
                    return [json.loads(clean_text[obj_start:obj_end])]
                except: pass
            raise ValueError("No valid JSON found.")
        
        return json.loads(clean_text[start:end])

class QuizService:
    def __init__(self, ai_provider: GenAIProvider):
        self.ai = ai_provider

    def calculate_topic_distribution(self, request: QuizRequest) -> Dict[str, int]:
        distribution = {}
        total = request.num_questions
        active = [t for t in request.topics if t.percentage > 0]
        if not active: return distribution
        
        assigned = 0
        for i, topic in enumerate(active[:-1]):
            count = (total * topic.percentage) // 100
            if count > 0:
                distribution[topic.topic_name] = count
                assigned += count
        
        if active: distribution[active[-1].topic_name] = total - assigned
        return distribution

    def _generate_with_retry(self, prompt: str, safe_prompt: str) -> str:
        try:
            return self.ai.generate_content(prompt, SYSTEM_INSTRUCTION, use_rag=True)
        except Exception as e:
            if "RECITATION_ERROR" in str(e):
                logger.warning("Generation hit Recitation error. Retrying.")
                return self.ai.generate_content(safe_prompt, SYSTEM_INSTRUCTION, use_rag=True)
            raise e

    def generate_from_ai(self, request: QuizRequest) -> List[QuizQuestion]:
        dist = self.calculate_topic_distribution(request)
        dist_str = "\n".join([f"- {c} questions about: {t}" for t, c in dist.items()])
        
        prompt = f"""
        Create a {request.num_questions} question multiple-choice quiz based ONLY on the provided File Store.
        DISTRIBUTION: {dist_str}
        OUTPUT SCHEMA (JSON Array): 
        [
            {{
                "question": "Question text...", 
                "options": ["A) ...", "B) ..."], 
                "correct_answer": "Full text of option", 
                "reference": "Rule #", 
                "explanation": "Concise explanation."
            }}
        ]
        """
        
        prompt_safe = f"""
        Create a {request.num_questions} question multiple-choice quiz.
        DISTRIBUTION: {dist_str}
        CRITICAL: Paraphrase all content. Do not quote source text directly.
        OUTPUT SCHEMA (JSON Array): ... (Same structure)
        """
        
        raw = self._generate_with_retry(prompt, prompt_safe)
        return [QuizQuestion(**i) for i in JSONParser.parse(raw)]
    
    def generate_scenarios(self, request: QuizRequest) -> List[QuizQuestion]:
        dist = self.calculate_topic_distribution(request)
        dist_str = "\n".join([f"- {c} scenarios involving: {t}" for t, c in dist.items()])
        
        prompt = f"""
        Create a {request.num_questions} question *Navigational Scenario Quiz* based on the File Store.
        DISTRIBUTION: {dist_str}
        INSTRUCTIONS: Create vivid scenarios (Bridge perspective). Ask for action/status.
        OUTPUT SCHEMA (JSON Array): 
        [
            {{
                "question": "Detailed scenario text...", 
                "options": ["A) ...", "B) ..."], 
                "correct_answer": "Full text of correct option", 
                "reference": "Rule #", 
                "explanation": "Concise explanation."
            }}
        ]
        """
        
        prompt_safe = f"""
        Create a {request.num_questions} question *Navigational Scenario Quiz*.
        DISTRIBUTION: {dist_str}
        CRITICAL: Invent NEW scenarios. Paraphrase all descriptions.
        OUTPUT SCHEMA (JSON Array): ... (Same structure)
        """
        
        raw = self._generate_with_retry(prompt, prompt_safe)
        return [QuizQuestion(**i) for i in JSONParser.parse(raw)]

    def generate_from_csv(self, raw_data: List[Dict], count: int) -> List[QuizQuestion]:
        prompt = f"""
        Convert this CSV data to JSON quiz. Use RAG for explanation/reference if missing.
        Data: {json.dumps(raw_data)}
        OUTPUT SCHEMA (JSON Array): [{{question, options[], correct_answer, reference, explanation}}]
        """
        
        prompt_safe = f"""
        Convert this CSV data to JSON quiz.
        Data: {json.dumps(raw_data)}
        CRITICAL: Paraphrase questions to avoid direct copying.
        OUTPUT SCHEMA (JSON Array): [{{question, options[], correct_answer, reference, explanation}}]
        """
        
        raw = self._generate_with_retry(prompt, prompt_safe)
        return [QuizQuestion(**i) for i in JSONParser.parse(raw)]

class RemediationService:
    """Generates lesson plans."""
    
    def __init__(self, ai_provider: GenAIProvider):
        self.ai = ai_provider

    def _generate_with_retry(self, prompt: str, safe_prompt: str) -> str:
        """Helper method to retry generation with a safe prompt if RECITATION_ERROR occurs."""
        try:
            return self.ai.generate_content(prompt, SYSTEM_INSTRUCTION, use_rag=True)
        except Exception as e:
            if "RECITATION_ERROR" in str(e):
                logger.warning("Generation hit Recitation error. Retrying with safe prompt.")
                try:
                    return self.ai.generate_content(safe_prompt, SYSTEM_INSTRUCTION, use_rag=True)
                except Exception as e2:
                    if "RECITATION_ERROR" in str(e2):
                        logger.error("Safe prompt also hit RECITATION_ERROR. Returning error message.")
                        return f"**Error: Unable to generate content due to recitation restrictions. Please try again.**"
                    raise e2
            raise e

    def _generate_batch_content(self, batch_refs: List[str]) -> str:
        topics = ", ".join(batch_refs)
        
        prompt = f"""
        Create a "Deep Dive" remediation section for Maritime Rules: {topics}.
        Based ONLY on the documents.
        Format: Markdown.
        For each: Header, Official Rule Text (Verbatim Quote), Explanation, Pitfalls, Memory Aid.
        """
        
        prompt_safe = f"""
        Create remediation for Maritime Rules: {topics}.
        Format: Markdown.
        CRITICAL: Paraphrase all rule text. Do not quote source text directly. Create original summaries.
        For each: Header, Rule Summary (Paraphrased), Explanation, Pitfalls, Memory Aid.
        """
        
        try:
            return self._generate_with_retry(prompt, prompt_safe)
        except Exception as e:
            logger.error(f"Error generating batch content for {topics}: {e}")
            return f"**Error generating content for {topics}: {str(e)}**"

    def generate_lesson(self, incorrect_questions: List[QuizQuestion]) -> str:
        unique_refs = sorted({q.reference for q in incorrect_questions if q.reference})
        if not unique_refs: return "No topics found."

        full_doc = ["# Remediation Lesson Plan", f"**Focus Topics:** {', '.join(unique_refs)}", "---"]
        
        batches = [unique_refs[i:i+REMEDIATION_BATCH_SIZE] for i in range(0, len(unique_refs), REMEDIATION_BATCH_SIZE)]
        
        with ThreadPoolExecutor(max_workers=MAX_PARALLEL_WORKERS) as executor:
            future_to_batch = {executor.submit(self._generate_batch_content, b): b for b in batches}
            results = []
            for future in as_completed(future_to_batch):
                try:
                    results.append((future_to_batch[future], future.result()))
                except: pass
        
        # Sort back to original order
        results.sort(key=lambda x: unique_refs.index(x[0][0]) if x[0] else 0)
        
        for _, content in results:
            full_doc.append(content)
            full_doc.append("\n---\n")
            
        return "\n\n".join(full_doc)

class OralBoardService:
    """Handles Oral Examination logic (Audio grading)."""
    
    def __init__(self, ai_provider: GenAIProvider):
        self.ai = ai_provider

    def _generate_with_retry(self, prompt: str, safe_prompt: str) -> str:
        """Helper method to retry generation with a safe prompt if RECITATION_ERROR occurs."""
        try:
            return self.ai.generate_content(prompt, SYSTEM_INSTRUCTION, use_rag=True)
        except Exception as e:
            if "RECITATION_ERROR" in str(e):
                logger.warning("Generation hit Recitation error. Retrying with safe prompt.")
                return self.ai.generate_content(safe_prompt, SYSTEM_INSTRUCTION, use_rag=True)
            raise e

    def generate_scenario(self) -> str:
        """Generates a complex oral exam scenario."""
        prompt = """
        Generate a specific, complex 'Oral Board' scenario for a Maritime Officer candidate.
        Subject: Rules of the Road / Collision Avoidance.
        
        Format the output clearly:
        **Scenario:** [Describe vessel status, visibility, other vessels, radar info, sound signals]
        **Question:** [What is the specific situation and what is your required action?]
        """
        
        prompt_safe = """
        Generate a specific, complex 'Oral Board' scenario for a Maritime Officer candidate.
        Subject: Rules of the Road / Collision Avoidance.
        
        CRITICAL: Paraphrase all content. Do not quote source text directly. Create original scenario descriptions.
        
        Format the output clearly:
        **Scenario:** [Describe vessel status, visibility, other vessels, radar info, sound signals]
        **Question:** [What is the specific situation and what is your required action?]
        """
        
        return self._generate_with_retry(prompt, prompt_safe)

    def grade_response(self, scenario: str, audio_bytes: bytes) -> str:
        """Grades the audio response against the scenario."""
        prompt = f"""
        You are a USCG Licensing Examiner.
        
        **SCENARIO GIVEN TO CANDIDATE:**
        {scenario}
        
        **TASK:**
        Listen to the candidate's audio response provided in the attachment.
        
        **OUTPUT FORMAT:**
        1. **Transcript:** Write down exactly what the candidate said.
        2. **Grade:** PASS or FAIL.
        3. **Critique:**
           - Did they identify the correct Rule?
           - Did they state the correct action?
           - Was the answer delivered confidently?
        4. **Correct Answer:** What was the expected response?
        """
        
        return self.ai.generate_content_with_audio(
            prompt=prompt, 
            audio_bytes=audio_bytes, 
            mime_type="audio/wav", # Streamlit audio recorder output
            system_instr=SYSTEM_INSTRUCTION
        )

# --- PRESENTATION LAYER ---

def init_session_state():
    defaults = {
        "messages": [{"role": "assistant", "content": "👋 Maritime Expert Ready."}],
        "quiz_data": None,
        "current_quiz_source": None,
        "incorrect_questions": [],
        "remediation_text": None,
        "oral_scenario": None,  # For Oral Board
        "oral_grade": None      # For Oral Board
    }
    for key, val in defaults.items():
        if key not in st.session_state:
            st.session_state[key] = val

def set_background():
    bin_str = DataManager.get_base64_image('background.png')
    if bin_str:
        st.markdown(f'''<style>
        .stApp {{ background-image: url("data:image/png;base64,{bin_str}"); background-size: cover; }}
        </style>''', unsafe_allow_html=True)

def render_oral_board(oral_service: OralBoardService):
    st.title("🎙️ Oral Board Simulator")
    st.caption("Simulate a USCG Licensing Exam. Speak your answer clearly.")
    
    col1, col2 = st.columns([1, 2])
    
    with col1:
        if st.button("🔄 Generate New Scenario", type="primary"):
            with st.spinner("Examiner is preparing a scenario..."):
                scenario = oral_service.generate_scenario()
                st.session_state.oral_scenario = scenario
                st.session_state.oral_grade = None # Reset previous grade
                st.rerun()

    if st.session_state.oral_scenario:
        st.markdown("### 📋 Examiner's Scenario")
        st.info(st.session_state.oral_scenario)
        
        st.markdown("### 🗣️ Your Response")
        audio_input = st.audio_input("Record your answer", key="audio_recorder")
        
        if audio_input:
            # Check if we already graded this specific audio (prevent re-run on simple interaction)
            if not st.session_state.oral_grade:
                with st.spinner("Examiner is listening and grading..."):
                    try:
                        # Read audio bytes and validate
                        # Try multiple methods to read the audio
                        if hasattr(audio_input, 'read'):
                            # Reset to beginning if it's a file-like object
                            if hasattr(audio_input, 'seek'):
                                audio_input.seek(0)
                            audio_bytes = audio_input.read()
                        elif hasattr(audio_input, 'getvalue'):
                            audio_bytes = audio_input.getvalue()
                        else:
                            audio_bytes = bytes(audio_input)
                        
                        logger.info(f"Audio input type: {type(audio_input)}, size: {len(audio_bytes) if audio_bytes else 0} bytes")
                        
                        if not audio_bytes:
                            st.error("❌ No audio data received. Please record your answer again.")
                        elif len(audio_bytes) < 100:
                            st.warning(f"⚠️ Audio file is very small ({len(audio_bytes)} bytes). Please record a longer response.")
                        else:
                            logger.info(f"Processing audio response: {len(audio_bytes)} bytes, first 20 bytes: {audio_bytes[:20]}")
                            grade = oral_service.grade_response(st.session_state.oral_scenario, audio_bytes)
                            st.session_state.oral_grade = grade
                    except ValueError as e:
                        if "RECITATION_ERROR" in str(e):
                            st.warning("⚠️ The examiner encountered an issue. Please try recording your answer again.")
                            logger.warning("RECITATION_ERROR in audio grading")
                        else:
                            st.error(f"❌ Validation error: {e}")
                    except Exception as e:
                        st.error(f"❌ Grading failed: {e}")
                        logger.error(f"Audio grading exception: {e}", exc_info=True)
            
            if st.session_state.oral_grade:
                st.divider()
                st.subheader("👨‍✈️ Examiner's Evaluation")
                st.markdown(st.session_state.oral_grade)

def main():
    st.set_page_config(page_title="RAG Engine", page_icon="⚓", layout="wide")
    set_background()
    init_session_state()
    
    try:
        ai_provider = GenAIProvider(st.secrets[API_KEY_NAME], st.secrets[STORE_ID_NAME])
        quiz_service = QuizService(ai_provider)
        remediation_service = RemediationService(ai_provider)
        oral_service = OralBoardService(ai_provider)
    except KeyError:
        st.error("Missing Secrets"); st.stop()

    with st.sidebar:
        st.title("⚓ Maritime AI")
        mode = st.radio("Tool:", ["Chat 🤖", "Quiz 📝", "Oral Board 🎙️"])
        if st.button("Reset Session"):
            st.session_state.clear()
            st.rerun()
        st.divider()
        st.caption("✅ v16.0 - Oral Board Active") 

    if mode == "Chat 🤖":
        st.title("Regulations Chat")
        for m in st.session_state.messages: st.chat_message(m["role"]).write(m["content"])
        if p := st.chat_input():
            st.session_state.messages.append({"role": "user", "content": p})
            st.chat_message("user").write(p)
            with st.spinner("Thinking..."):
                try:
                    r = ai_provider.generate_content(p, SYSTEM_INSTRUCTION)
                    st.session_state.messages.append({"role": "assistant", "content": r})
                    st.chat_message("assistant").write(r)
                except Exception as e:
                    st.error(f"Error: {e}")

    elif mode == "Quiz 📝":
        # ... (Existing Quiz Logic kept identical, summarized for brevity) ...
        # Note: I'm keeping your exact logic here, just ensuring indentation fits
        st.title("Knowledge Check")
        def clear(): 
            st.session_state.quiz_data = None
            st.session_state.incorrect_questions = []
            st.session_state.remediation_text = None

        source = st.radio("Source:", ["CSV", "AI Gen"], horizontal=True, on_change=clear, key="source_radio")
        
        if source == "CSV":
            tags = st.multiselect("Topics:", DataManager.get_topics_from_csv("ror_test.csv"))
            n = st.number_input("Count:", 1, 25, 5)
            if st.button("Load CSV") and tags:
                try:
                    data = DataManager.load_csv_sample("ror_test.csv", tags, n)
                    if data:
                        with st.spinner("Generating..."):
                            st.session_state.quiz_data = quiz_service.generate_from_csv(data, n)
                            st.session_state.current_quiz_source = "CSV"
                            st.rerun()
                    else: st.warning("No data.")
                except Exception as e: st.error(f"Error: {e}")
        else:
            quiz_style = st.radio("Style:", ["Standard Rules", "Applied Scenarios"], horizontal=True)
            topics = []
            for i in range(1, 5):
                c1, c2 = st.columns([3, 1])
                t = c1.text_input(f"Topic {i}")
                p = c2.number_input(f"%", 0, 100, 0, key=f"p{i}")
                if t: topics.append(TopicDistribution(topic_name=t, percentage=p))
            n = st.number_input("Count", 1, 25, 5)
            
            if st.button(f"Generate {quiz_style}"):
                with st.spinner("Generating..."):
                    try:
                        req = QuizRequest(num_questions=n, topics=topics)
                        if quiz_style == "Standard Rules":
                            st.session_state.quiz_data = quiz_service.generate_from_ai(req)
                        else:
                            st.session_state.quiz_data = quiz_service.generate_scenarios(req)
                        st.session_state.current_quiz_source = f"AI ({quiz_style})"
                        st.rerun()
                    except Exception as e: st.error(f"Error: {e}")

        if st.session_state.quiz_data:
            with st.form("quiz"):
                score = 0
                answers = {}
                for i, q in enumerate(st.session_state.quiz_data):
                    st.markdown(f"**{i+1}. {q.question}**")
                    answers[i] = st.radio("Opt", q.options, key=f"q{i}", label_visibility="collapsed", index=None)
                    st.write("---")
                if st.form_submit_button("Submit"):
                    inc = []
                    for i, q in enumerate(st.session_state.quiz_data):
                        if answers.get(i) == q.correct_answer:
                            score += 1
                            st.success(f"Q{i+1} Correct!")
                        else:
                            st.error(f"Q{i+1} Incorrect")
                            st.write(f"**Correct:** {q.correct_answer}")
                            inc.append(q)
                        with st.expander("Explanation"): st.info(f"{q.explanation} ({q.reference})")
                    
                    st.session_state.incorrect_questions = inc
                    st.session_state.remediation_text = None
                    st.metric("Score", f"{score}/{len(st.session_state.quiz_data)}")

            if st.session_state.incorrect_questions:
                st.divider()
                st.subheader("🎓 Remediation Zone")
                if st.button("Generate Remediation Lesson"):
                    with st.spinner("Generating..."):
                        try:
                            lesson = remediation_service.generate_lesson(st.session_state.incorrect_questions)
                            st.session_state.remediation_text = lesson
                        except Exception as e: st.error(f"Error: {e}")
                
                if st.session_state.remediation_text:
                    st.markdown("---")
                    st.markdown(st.session_state.remediation_text)
                    if HAS_REPORTLAB:
                        pdf = PDFGenerator.create_study_guide(st.session_state.remediation_text)
                        if pdf: st.download_button("Download PDF", pdf, "remediation.pdf", "application/pdf")
                    
                    st.divider()
                    st.subheader("📝 Practice Makes Perfect")
                    
                    missed_refs = sorted({q.reference for q in st.session_state.incorrect_questions if q.reference})
                    
                    c1, c2 = st.columns([3, 1])
                    with c1:
                        st.info(f"Target Topics: {', '.join(missed_refs)}" if missed_refs else "Target Topics: General Review")
                    with c2:
                        rem_n = st.number_input("Questions:", REMEDIATION_QUIZ_MIN, REMEDIATION_QUIZ_MAX, DEFAULT_QUIZ_COUNT, key="rem_n")
                    
                    rem_style = st.radio("Remediation Style:", ["Standard Rules", "Applied Scenarios"], horizontal=True, key="rem_style")

                    if st.button("Start Remediation Quiz"):
                        try:
                            topics = []
                            if missed_refs:
                                count = len(missed_refs)
                                base_pct = 100 // count
                                remainder = 100 % count
                                for i, ref in enumerate(missed_refs):
                                    pct = base_pct + (1 if i < remainder else 0)
                                    topics.append(TopicDistribution(topic_name=ref, percentage=pct))
                            else:
                                topics.append(TopicDistribution(topic_name="General Maritime Rules", percentage=100))
                            
                            req = QuizRequest(num_questions=rem_n, topics=topics)
                            
                            with st.spinner("Generating targeted practice quiz..."):
                                if rem_style == "Standard Rules":
                                    new_quiz = quiz_service.generate_from_ai(req)
                                else:
                                    new_quiz = quiz_service.generate_scenarios(req)
                                
                                st.session_state.quiz_data = new_quiz
                                st.session_state.current_quiz_source = f"Remediation ({rem_style})"
                                st.session_state.incorrect_questions = []
                                st.session_state.remediation_text = None
                                st.rerun()
                                
                        except ValueError as e:
                            if "RECITATION_ERROR" in str(e):
                                st.error("The AI attempted to copy too much text. Please try generating the quiz again.")
                            else:
                                st.error(f"Error: {e}")
                        except Exception as e:
                            st.error(f"System Error: {e}") 

            with st.expander("Admin"):
                st.download_button("JSON", json.dumps([q.model_dump() for q in st.session_state.quiz_data], indent=2), "quiz.json")

    elif mode == "Oral Board 🎙️":
        render_oral_board(oral_service)

if __name__ == "__main__":
    main()